#!/usr/bin/env python

import rospy
from std_srvs.srv import Empty, EmptyResponse

import os
import glob

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage

sender_email_ = "guardiansurveillance.ai@gmail.com"
sender_password_ = "t2vqh97u"
receiver_email_ = "joeyyang.ai@gmail.com"
starttls_port_ = 587
smtp_server_ = "smtp.gmail.com"

msg_ = MIMEMultipart()
msg_["X-Priority"] = "1"
msg_["From"] = sender_email_
msg_["To"] = receiver_email_
msg_["Subject"] = "Urgent!"

text_ = MIMEText("Warning! Intruder(s) Detected!")
msg_.attach(text_)

def getImageFile():
    all_image_files = glob.glob("/home/ubuntu/catkin_ws/src/guardian_surveillance/media/*.jpg")
    image_file_ = max(all_image_files, key=os.path.getctime)   
    return image_file_

def sendEmail(image):
    msg_.attach(image)
    server = smtplib.SMTP(smtp_server_, starttls_port_)
    server.starttls()
    server.login(sender_email_, sender_password_)
    server.sendmail(sender_email_, receiver_email_, msg_.as_string())
    server.quit()

def emailAlertCb(request):
    """rospy.wait_for_service("/image_saver/save")
    save_image = rospy.ServiceProxy("/image_saver/save", Empty, persistent=True)
    save_image()"""
    image_file_ = getImageFile()
    image = MIMEImage(open(image_file_, "rb").read(), name=os.path.basename(image_file_))
    sendEmail(image)
    return EmptyResponse()

def emailAlertServer():
    rospy.init_node("email_alert_node")
    email_alert_server = rospy.Service("email_alert", Empty, emailAlertCb)
    rospy.spin()

if __name__ == '__main__':
    emailAlertServer()
   
