#!/usr/bin/env python

import rospy
from im

import os
from twilio.rest import Client

import smtplib
from email.message import Message #EmailMessage

"""account_sid = os.environ['TWILIO_ACCOUNT_SID']
auth_token = os.environ['TWILIO_AUTH_TOKEN']

client = Client(account_sid, auth_token)
client.messages.create(
  to = "+16479663926",
  from_ = "+16475030604",
  body = "ALERT: INTRUDER DETECTED BY GUARDIAN SURVEILLANCE"
)

sender_email = "guardiansurveillance.ai@gmail.com"
sender_password = "t2vqh97u"
receiver_email = "joeyyang.ai@gmail.com"
starttls_port = 587
smtp_server = "smtp.gmail.com"

msg = Message() #EmailMessage()
msg["X-Priority"] = "1"
msg["From"] = sender_email
msg["To"] = receiver_email
msg["Subject"] = "Urgent!"
msg.set_content("ALERT: INTRUDER DETECTED BY GUARDIAN SURVEILLANCE")

server = smtplib.SMTP(smtp_server, starttls_port)
server.starttls()
server.login(sender_email, sender_password)
server.sendmail(sender_email, receiver_email, msg.as_string())
server.quit()"""

def emailAlert():
    #rospy.init_node("email_alert_node", anonymous = True)
    rospy.spin()

if __name__ == '__main__':
    emailAlert()
