#!/usr/bin/env python

import rospy
from std_srvs.srv import Empty, EmptyResponse

import os
from twilio.rest import Client

account_sid_ = os.environ["TWILIO_ACCOUNT_SID"]
auth_token_ = os.environ["TWILIO_AUTH_TOKEN"]

client_ = Client(account_sid_, auth_token_)

def textAlertCb(request):
  client_.messages.create(
    to = os.environ["USER_PHONE_NUMBER"],
    from_ = os.environ["TWILIO_PHONE_NUMBER"],
    body = "ALERT: INTRUDER DETECTED BY GUARDIAN SURVEILLANCE"
  )
  return EmptyResponse()

def textAlertServer():
  rospy.init_node("text_alerter_node")
  text_alert_server = rospy.Service("text_alerter", Empty, textAlertCb)
  rospy.spin()

if __name__ == '__main__':
  textAlertServer()
